// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250611190209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Class.TB_BOOKING", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BOOKINGDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("PROPERTYID")
                        .HasColumnType("int");

                    b.Property<int>("STATUS")
                        .HasColumnType("int");

                    b.Property<Guid>("USERID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("TB_BOOKING", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("e8c4c038-04e9-4f1b-8f97-07f68b74e5bb"),
                            BOOKINGDATE = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            PROPERTYID = 1,
                            STATUS = 0,
                            USERID = new Guid("7fc7cf98-fb79-4e4e-9b87-8f7415c53127")
                        },
                        new
                        {
                            ID = new Guid("a4eb2283-f1c1-4f1c-a003-b765f91a77f4"),
                            BOOKINGDATE = new DateTime(2025, 6, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            PROPERTYID = 2,
                            STATUS = 1,
                            USERID = new Guid("f9e2f74d-8327-44c3-a676-fc4e3a9ffae2")
                        },
                        new
                        {
                            ID = new Guid("45a8ae32-d47c-408c-950c-064f7d91126b"),
                            BOOKINGDATE = new DateTime(2025, 6, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PROPERTYID = 3,
                            STATUS = 2,
                            USERID = new Guid("9d7164e0-19e1-4f16-9343-1a9d2c1c055a")
                        },
                        new
                        {
                            ID = new Guid("5f989dd7-712b-4a9f-891c-4a4476f2fa8d"),
                            BOOKINGDATE = new DateTime(2025, 6, 4, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            PROPERTYID = 4,
                            STATUS = 1,
                            USERID = new Guid("7fc7cf98-fb79-4e4e-9b87-8f7415c53127")
                        });
                });

            modelBuilder.Entity("WebApplication1.Class.TB_PROPERTY", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ISAVILABLE")
                        .HasColumnType("bit");

                    b.Property<string>("LOCATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PRICE")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("TB_PROPERTYS", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("f0a0c92b-7f5e-43a4-9501-bb445ac6ab81"),
                            ISAVILABLE = false,
                            LOCATION = "Los Angeles",
                            NAME = "Sunset Villa",
                            PRICE = 250000.00m
                        },
                        new
                        {
                            ID = new Guid("24c771fc-3e5e-4de2-bc6a-e5c880894263"),
                            ISAVILABLE = false,
                            LOCATION = "Miami",
                            NAME = "Ocean Breeze Apartment",
                            PRICE = 180000.00m
                        },
                        new
                        {
                            ID = new Guid("5d7b3280-7125-4f40-bcc0-b19ad66e5738"),
                            ISAVILABLE = false,
                            LOCATION = "Denver",
                            NAME = "Mountain Retreat",
                            PRICE = 320000.00m
                        },
                        new
                        {
                            ID = new Guid("109e3fcd-f279-4a36-b34a-6224ed264b7c"),
                            ISAVILABLE = false,
                            LOCATION = "New York",
                            NAME = "City Loft",
                            PRICE = 500000.00m
                        });
                });

            modelBuilder.Entity("WebApplication1.Class.TB_USER", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FULLNAME")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PASSWORDHASH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ROLE")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TB_USERS", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("7fc7cf98-fb79-4e4e-9b87-8f7415c53127"),
                            EMAIL = "John2@yahoo.com",
                            FULLNAME = "John",
                            PASSWORDHASH = "123",
                            ROLE = 1
                        },
                        new
                        {
                            ID = new Guid("f9e2f74d-8327-44c3-a676-fc4e3a9ffae2"),
                            EMAIL = "jane2@yahoo.com",
                            FULLNAME = "Jane Smith",
                            PASSWORDHASH = "456",
                            ROLE = 2
                        },
                        new
                        {
                            ID = new Guid("9d7164e0-19e1-4f16-9343-1a9d2c1c055a"),
                            EMAIL = "mike3@gmai.com",
                            FULLNAME = "Mike Brown",
                            PASSWORDHASH = "A425",
                            ROLE = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
